/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bf.pd;

import de.odysseus.ithaka.audioinfo.AudioInfo;
import de.odysseus.ithaka.audioinfo.m4a.M4AInfo;
import de.odysseus.ithaka.audioinfo.mp3.ID3v2Exception;
import de.odysseus.ithaka.audioinfo.mp3.MP3Exception;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.stream.Collectors;

public class AudioCheck {

    public static void main(String[] args) throws Exception {
        checkM4a();
    }


    private static void checkM4a() throws IOException, ID3v2Exception, MP3Exception {
        ArrayList<Path> files = Files.walk(Paths.get("c:\\media\\podcast\\"))
                .filter((path) -> {
                    String pathStr = path.toString();
                    return
                            !pathStr.contains("ljsw")
                                    && !pathStr.contains("S05E01")
                                    && !pathStr.endsWith(".bat")
                                    && Files.isRegularFile(path);
                })
                .collect(Collectors.toCollection(ArrayList::new));

        InputStream inputStream;
        for (Path path : files) {
            File file = path.toFile();
            inputStream = new BufferedInputStream(new FileInputStream(file));
            AudioInfo audioInfo;

            try {
                audioInfo = new M4AInfo(inputStream);
            } catch (IOException e) {
                System.out.println(file);
                continue;
            } finally {
                inputStream.close();
            }

            long fileLength = file.length();

            double x = fileLength / audioInfo.getDuration();
            if (x < 8) {
                System.out.println(file.getAbsolutePath() + ": " + x);
                java.awt.Desktop.getDesktop().moveToTrash(path.toFile());
            }
        }
    }
}
