/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bf.pd;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

public class CleanFiles {


    public static void main(String[] args) throws Exception {


        Files.walk(Paths.get("C:\\media\\CloudMusic\\"))
                .filter((path) ->  path.toFile().getName().endsWith(".mp3"))
                .forEach(path -> {
                    String name = path.toFile().getName();
                    if (!name.contains("-")) {
                        try {
                            Files.deleteIfExists(path);
                        } catch (IOException e) {
                            System.out.println("error delete:" + path);
                        }
                    }
                });
    }
}
