/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bf.pd;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

public class CleanFiles {


    public static void main(String[] args) throws Exception {

        List<String> blackLists = Files.readAllLines(Path.of("blacklist.properties"));

        Files.walk(Paths.get("c:\\media\\podcast\\"))
                .filter((path) -> path.toFile().getName().endsWith(".m4a"))
                .forEach(path -> {
                    String name = path.toFile().getName();
                    name = name.substring(0, name.lastIndexOf(".m4a"));
                    for (String s : blackLists) {
                        if (name.contains(s)) {
                            java.awt.Desktop.getDesktop().moveToTrash(path.toFile());
                            System.out.println(path + " deleted");
                        }
                    }
                });
    }
}
