/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bf.pd;


public class Downloader {
    public static void main(String[] args) throws Exception {
        String[] urls = {
                "https://www.ximalaya.com/waiyu/15268893/",
        };

        for (String url : urls) {
            DownXmly.main(new String[]{url});
        }
    }
}
