/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bf.pd;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.commons.io.FileUtils;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.nio.file.Files;
import java.util.Map;

public class DownXmly {

    public static void main(String[] args) throws Exception {
        if (args.length != 1) {
            System.out.println("input album url");
            return;
        }
        String albumUrl = args[0];

        boolean hasNext = true;
        int pageNum = 1;
        while (hasNext) {
            hasNext = onePage(albumUrl + "p" + pageNum + "/", pageNum);
            pageNum++;
        }
    }

    private static boolean onePage(String albumUrl, int pageNum) throws Exception {
        System.out.println(albumUrl);
        String[] split = albumUrl.split("https://www.ximalaya.com/");
        String s = split[1].split("/")[1];
        int albumNum = Integer.parseInt(s);

        Document page = JsoupUtil.urlToDoc(albumUrl);

        Elements tracks = page.select("#anchor_sound_list > div.sound-list._Qp > ul > li> div.text._Vc > a");
        System.out.println(page.select("head > title").html());
        if (tracks.size() == 0 && pageNum == 1) throw new Exception("empty list:" + albumUrl);
        boolean hasNext = false;
        for (Element track : tracks) {
            String href = track.attr("href");
            String[] tried = href.split("/" + albumNum + "/");
            if (tried.length == 1)
                continue;
            String trackNum = tried[1];
            String trackUrl = "http://www.ximalaya.com/tracks/" + trackNum + ".json";
            String json = HttpUtil.url2Body(trackUrl);
            ObjectMapper mapper = new ObjectMapper();
            Map map = mapper.readValue(json, Map.class);
            String audioUrl = (String) map.get("play_path_64");
            String title = (String) map.get("title");
            if (title.contains("直播回听")) continue;
            if (title.contains("问题征集活动")) continue;
            title = title.replaceAll("\"", "");
            title = title.replaceAll("\\?", "");
            title = title.replaceAll("\\|", "");
            title = title.replaceAll("/", "");

            System.out.println(title);

            String albumTitle = (String) map.get("album_title");
            albumTitle = albumTitle.replaceAll("\\|", "");
            File folder = new File("C:\\media\\podcast\\" + albumTitle);
            Files.createDirectories(folder.toPath());

            File toDownload = new File(folder + "/" + title + ".m4a");
            if (toDownload.exists()) {
                if (toDownload.length() == 0) {
                    boolean delete = toDownload.delete();
                    System.out.println(toDownload + " size 0, deleted:" + delete);
                }
            }

            if (!toDownload.exists()) {
                try {
                    FileUtils.copyURLToFile(new URL(audioUrl), toDownload);
                } catch (IOException e) {
                    System.out.println(e.getMessage());
                }
                System.out.println(title);
            }
            hasNext = true;
        }
        return hasNext;
    }
}
