/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bf.pd;


import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class Downloader {
    public static void main(String[] args) {
        String[] urls = {
                "https://www.ximalaya.com/waiyu/9268928/",
        };

        ExecutorService executorService = Executors.newFixedThreadPool(urls.length);
        for (String url : urls) {
            executorService.submit(() -> {
                try {
                    DownXmly.main(new String[]{url});
                } catch (Exception e) {
                    e.printStackTrace();
                }
            });
        }

        executorService.shutdown();
        while (!executorService.isTerminated()) {
        }
    }
}
