/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bf.pd;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.github.houbb.opencc4j.util.ZhConverterUtil;
import org.apache.commons.io.FileUtils;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.nio.file.Files;
import java.util.Map;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class DownXmly {


    public static void main(String[] args) {

        if (args.length != 1) {
            System.out.println("DownXmly url");
            return;
        }

        String albumUrl = args[0];
        if (!albumUrl.endsWith("/")) albumUrl += "/";

        int pageCount = getPageCount(albumUrl);
        for (int i = 1; i <= pageCount + 1; i++) {
            onePage(albumUrl + "p" + i + "/", i);
        }
    }

    static int getPageCount(String albumUrl) {
        Document document = JsoupUtil.urlToDoc(albumUrl);
        String tracksNodeValue = document.select("#anchor_sound_list > div.head._is span").text();
        String tracksCountString = tracksNodeValue.split("声音（")[1].split("）")[0];
        int tracksCount = Integer.parseInt(tracksCountString.trim());
        System.out.println("total tracks:" + tracksCount);
        return tracksCount / 30;
    }

    private static void onePage(String albumUrl, int pageNum) {
        System.out.println(albumUrl);
        String[] split = albumUrl.split("https://www.ximalaya.com/");
        String s = split[1].split("/")[1];
        int albumNum = Integer.parseInt(s);

        Document page = JsoupUtil.urlToDoc(albumUrl);

        Elements tracks = page.select("#anchor_sound_list > div.sound-list._is > ul > li > div.text.lF_ > a");
        String albumName = page.select("head > title").html();
        System.out.println(albumName);
        if (tracks.size() == 0) {
            if (pageNum == 1)
                throw new RuntimeException("empty list:" + albumUrl);
            else
                return;
        }

        ExecutorService executorService = Executors.newFixedThreadPool(5);
        for (Element track : tracks) {
            executorService.submit(() -> {
                try {
                    downloadTrack(track);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            });
        }
        executorService.shutdown();
        while (!executorService.isTerminated()) {
        }
    }

    private static void downloadTrack(Element track) {
        String href = track.attr("href");
        String trackNum = href.substring(href.lastIndexOf("/") + 1);
        String trackUrl = "http://www.ximalaya.com/tracks/" + trackNum + ".json";
        String json = HttpUtil.url2Body(trackUrl);
        ObjectMapper mapper = new ObjectMapper();
        Map map = null;
        try {
            map = mapper.readValue(json, Map.class);
        } catch (JsonProcessingException e) {
            throw new RuntimeException(e);
        }
        String audioUrl = (String) map.get("play_path_64");
        if (audioUrl == null) {
            System.out.println(trackNum + ".json has error, skip");
            return;
        }

        String title = (String) map.get("title");
        title = cleanFileName(title);
        title = ZhConverterUtil.toSimple(title);

        String albumTitle = (String) map.get("album_title");
        albumTitle = cleanFileName(albumTitle);
        File folder = new File("C:\\media\\podcast\\" + albumTitle);
        try {
            Files.createDirectories(folder.toPath());
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        File toDownload = new File(folder + "/" + title + ".m4a");

        if (!toDownload.exists()) {
            System.out.println(title);
            try {
                FileUtils.copyURLToFile(new URL(audioUrl), toDownload);
            } catch (IOException e) {
                deleteFile(toDownload);
                throw new RuntimeException(e);
            }
        }
    }

    private static String cleanFileName(String title) {
        title = title.replaceAll("\"", "_");
        title = title.replaceAll("\\?", "？");
        title = title.replaceAll("\\|", "");
        title = title.replaceAll("/", "_");
        title = title.replaceAll(":", "：");
        return title;
    }

    private static void deleteFile(File toDownload) {
        if (toDownload.exists()) {
            boolean delete = toDownload.delete();
            System.out.println(toDownload + " deleted:" + delete);
        }
    }
}
