/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bf.pd;

import com.github.houbb.opencc4j.util.ZhConverterUtil;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.stream.Collectors;

public class FormatNames {


    public static void main(String[] args) throws Exception {
        String[] paths = {"C:\\media\\download\\"};
        for (String path : paths) {
            ArrayList<Path> list = Files.walk(Paths.get(path))
                    .filter(Files::isRegularFile)
                    .collect(Collectors.toCollection(ArrayList::new));
            for (Path p : list) {
                String test = p.toFile().getName();
                String formatted = ZhConverterUtil.toSimple(test);
                formatted = format(formatted);
                if (!test.equals(formatted)) {
                    if (!Files.exists(p.resolveSibling(formatted))) {
                        Files.move(p, p.resolveSibling(formatted));
                        System.out.println(p);
                    }
                }
            }
        }

    }

    private static String format(String toFormat) {
        String s = toFormat.replaceAll("叶蒨文", "叶倩文");
        s = s.replaceAll("^Hua Chen Yu", "华晨宇");
        s = s.replaceAll("^Faye Wong", "王菲");
        s = s.replaceAll("^Eason Chan", "陈奕迅");
        s = s.replaceAll("^Tanya Chua", "蔡健雅");
        s = s.replaceAll("^A-do", "阿杜");
        s = s.replaceAll("^Jacky Cheung", "张学友");
        s = s.replaceAll("^Ke\\$ha", "Kesha");
        s = s.replaceAll("^AC-DC", "AC／DC");
        s = s.replaceAll("^Kelly Yu", "于文文");
        s = s.replaceAll("^黄沾", "黄霑 ");
        s = s.replaceAll("^GEM", "G.E.M.邓紫棋");
        s = s.replaceAll("^LaLa Hsu", "徐佳莹");
        s = s.replaceAll("^Fish Leong", "梁静茹");
        s = s.replaceAll("^Steve Chou", "周传雄");
        s = s.replaceAll("^Christine Fan", "范玮琪");
        s = s.replaceAll("^CORSAK", "胡梦周");
        s = s.replaceAll("^Hebe Tien", "田馥甄");
        s = s.replaceAll("^Jay Chou", "周杰伦");
        s = s.replaceAll("^Jenny Tseng", "甄妮");
        s = s.replaceAll("^Wanting", "曲婉婷");
        s = s.replaceAll("^Rene Liu", "刘若英");
        s = s.replaceAll("^Wang Feng", "汪峰");
        s = s.replaceAll("^Angela Chang", "张含韵");
        s = s.replaceAll("^Jike Junyi", "吉克隽逸");
        s = s.replaceAll("^Mayday", "五月天");
        s = s.replaceAll("^Sue - ", "苏运莹 - ");
        s = s.replaceAll("^Aska Yang", "杨宗纬");
        s = s.replaceAll("^JJ Lin", "林俊杰");
        s = s.replaceAll("^Silence Wang", "汪苏泷");
        s = s.replaceAll("^Tia Ray", "袁娅维");
        return s;
    }

}
