/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bf.pd;

import java.util.HashMap;
import java.util.Set;

public class XiangShengDownloader {

    private static HashMap<String, Set<String>> downLoadedTracks;
    private static Set<String> artistWhiteList;
    private static Set<String> trackWhiteList;

    public static void main(String[] args) throws Exception {

        String[] urls = {
                "https://www.ximalaya.com/xiangsheng/20788632/",
        };

        for (String url : urls) {
            XiangSheng.main(new String[]{url});
        }
    }
}
