/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bf.xmly;

import org.junit.Test;

import static org.junit.Assert.*;

public class AppTest {
  @Test
  public void run() throws Exception {
    String[][] urls = {
        { "https://www.ximalaya.com/keji/246622/" },//原来是这样
        { "https://www.ximalaya.com/keji/5411224/" },//科学史评话最新专辑
        { "https://www.ximalaya.com/keji/4769101" }//思考盒子
    };
    for (String[] url : urls) {
      App.main(url);
    }
  }
}
