/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bf.xmly;

import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

public class AudioCheckWithFoobar {

    public static void main(String[] args) throws Exception {
        StringBuilder sb = new StringBuilder();

        List<String> lines = Files.readAllLines(Paths.get("C:\\media\\podcast\\ljsw\\validate.txt"));
        for (int i = 0; i < lines.size(); i++) {
            String line = lines.get(i);
            if (!line.contains("Item:")) continue;
            String nextLine = lines.get(i + 1);
            if (nextLine.equals("No problems found.")) continue;
            line = line.split("Item: \"")[1].split("\"")[0];
            System.out.println(line);
            Files.delete(Paths.get(line));
        }

        if (sb.length() > 0)
            Files.writeString(Paths.get("error.log"), sb.toString());
    }
}
