/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bf.xmly;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.stream.Collectors;

public class FilesCount {

    public static final int COUNT = 1079;

    public static void main(String[] args) throws Exception {
        ArrayList<Path> files = Files.walk(Paths.get("c:\\media\\podcast\\ljsw"))
                .filter(Files::isRegularFile)
                .collect(Collectors.toCollection(ArrayList::new));
        int[] map = new int[COUNT];
        for (Path path : files) {
            String s = path.toString();
            s = s.split("NO.")[1];
            s = s.split(" ")[0];
            int i = Integer.parseInt(s);
            map[i]++;
        }

        for (int i = 1; i < COUNT; i++) {
            if (map[i] == 0) System.out.println(i);
        }
    }

    private static void count() throws IOException {
        ArrayList<Path> files = Files.walk(Paths.get("c:\\media\\podcast\\罗辑思维"))
                .filter(Files::isRegularFile)
                .collect(Collectors.toCollection(ArrayList::new));
        int[] map = new int[206];
        for (Path path : files) {
            String s = path.toString();
            if (s.contains("2015")) continue;
            s = s.replace("  ", " ");
            String splicer = " ";
            s = s.split(splicer)[1];
            int i = Integer.parseInt(s);
            map[i]++;
        }

        for (int i = 1; i < 206; i++) {
            if (map[i] == 0) System.out.println(i);
        }
    }
}
