/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bf.pd;

import org.junit.Test;

public class XmlyTest {
    @Test
    public void run() throws Exception {
        SQLiteJDBC.main(null);
        String[][] urls = {
                {"https://www.ximalaya.com/keji/20486769/"},
                {"https://www.ximalaya.com/keji/246622/"},
                {"https://www.ximalaya.com/keji/5411224/"},
                {"https://www.ximalaya.com/keji/4310827/"},
                {"https://www.ximalaya.com/keji/4769101/"},
                {"https://www.ximalaya.com/keji/21469108/"},
        };
        for (String[] url : urls) {
            DownXmly.main(url);
        }
    }
}
